name: .NET CI Build 
on: 
  push: 
   branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 
jobs: 
  build: 
    runs-on: windows-latest 
    
    steps: 
     - name: Checkout Repository 
       uses: actions/checkout@v4 
     
     - name: ️Setup .NET 
       uses: actions/setup-dotnet@v4 
       with: 
        dotnet-version: '6.0.x' 
        
     - name: Restore Dependencies
       run: dotnet restore 
      
     - name:  Build Project 
       run: dotnet build --configuration Release --no-restore 
      
     - name: Run Tests (if any) 
       run: dotnet test --no-build --verbosity normal
